greeting:
  message: server-native=hello

---
spring:
  config:
    activate:
      on-profile: hello

greeting:
  message: server-native-p:hello=hello

---
spring:
  config:
    activate:
      on-profile: world

greeting:
  message: server-native-p:world=hello