name: Release Scheduler

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Profile (prod/dev)'
        required: true
        type: choice
        options:
          - prod
          - dev
  workflow_call:
    inputs:
      profile:
        description: 'Profile (prod/dev)'
        required: true
        type: string

jobs:
  print-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get current branch and pass to shell script
        run: |
          echo "Running on branch: $GITHUB_REF"
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "Branch name is: $BRANCH_NAME"
